spring:
  application:
    name: Staffing_Management_backend
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    uri: "${MONGODB_URI}"

jwt:
  secret: "${JWT_SECRET}"
  expiration: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
logging:
  level:
    org.springframework.security: INFO
    com.staffing.allocation: DEBUG

app:
  admin:
    username: ${APP_ADMIN_USERNAME:admin}
    email: ${APP_ADMIN_EMAIL:admin@staffing.local}
    password: ${APP_ADMIN_PASSWORD}